rust: macros: rewrite `#[pinned_drop]` using `syn`
Now that `syn` and `quote` are available in the Kernel use them for the
`#[pinned_drop]` proc-macro attribute instead of the current hybrid
proc-macro/declarative approach.

Proc-macros written using `syn` are a lot more readable and thus easier
to maintain than convoluted declarative macros. An additional advantage
of `syn` is the improved error reporting, here is an example:

    #[pin_data(PinnedDrop)]
    struct Foo {}

    #[pinned_drop]
    impl PinnedDrop for Foo {}

Prior to this patch, the error reads:

    error: no rules expected the token `)`
       --> samples/rust/rust_minimal.rs:43:1
        |
    43  | #[pinned_drop]
        | ^^^^^^^^^^^^^^ no rules expected this token in macro call
        |
    note: while trying to match `fn`
       --> rust/kernel/init/macros.rs:511:13
        |
    511 |             fn drop($($sig:tt)*) {
        |             ^^
        = note: this error originates in the attribute macro `pinned_drop` (in Nightly builds, run with -Z macro-backtrace for more info)

    error[E0277]: the trait bound `Foo: PinnedDrop` is not satisfied
      --> samples/rust/rust_minimal.rs:40:1
       |
    40 | #[pin_data(PinnedDrop)]
       | ^^^^^^^^^^^^^^^^^^^^^^^
       | |
       | the trait `PinnedDrop` is not implemented for `Foo`
       | required by a bound introduced by this call
       |
       = note: this error originates in the macro `$crate::__pin_data` which comes from the expansion of the attribute macro `pin_data` (in Nightly builds, run with -Z macro-backtrace for more info)

    error: aborting due to 2 previous errors

After this patch, the error reads:

    error: Expected exactly one function in the `PinnedDrop` impl.
      --> samples/rust/rust_minimal.rs:44:25
       |
    44 | impl PinnedDrop for Foo {}
       |                         ^^

    error: aborting due to 1 previous error

Signed-off-by: Benno Lossin <benno.lossin@proton.me>