rust: macros: rewrite `Zeroable` derive macro using `syn`
Now that `syn` and `quote` are available in the Kernel use them for the
`Zeroable` derive macro instead of the current hybrid
proc-macro/declarative approach.

Proc-macros written using `syn` are a lot more readable and thus easier
to maintain than convoluted declarative macros. An additional advantage
of `syn` is the improved error reporting, here is an example:

    #[derive(Zeroable)]
    enum Foo {
        A,
        B
    }

Prior to this patch, the error reads:

    error: no rules expected the token `enum`
        --> samples/rust/rust_minimal.rs:41:1
         |
    41   | enum Foo {
         | ^^^^ no rules expected this token in macro call
         |
    note: while trying to match `struct`
        --> rust/kernel/init/macros.rs:1373:22
         |
    1373 |             $vis:vis struct $name:ident
         |                      ^^^^^^

    error: aborting due to 1 previous error

After this patch, the error reads:

    error: `Zeroable` can only be derived for structs.
      --> samples/rust/rust_minimal.rs:41:1
       |
    41 | / enum Foo {
    42 | |     A,
    43 | |     B
    44 | | }
       | |_^

    error: aborting due to 1 previous error

Signed-off-by: Benno Lossin <benno.lossin@proton.me>